In [2]:
import pandas as pd
import numpy as np
import folium
from googletrans import Translator
import mysql.connector as conn

In [71]:
poblacion= pd.read_csv("poblacion.csv")
alcohol= pd.read_csv("HappinessAlcoholConsumption.csv")
deaths= pd.read_csv("all_weekly_excess_deaths.csv")
medallas= pd.read_csv("medallas.csv")

In [72]:
poblacion

                                    PAÍS      POBLACIÓN
0                                  China  1,439,323,774
1                                  India  1,380,004,385
2                          United States    331,002,647
3                              Indonesia    273,523,621
4                               Pakistan    220,892,331
..                                   ...            ...
195                                Aruba        106,766
196                                Tonga        105,697
197  Virgin Islands of the United States        104,423
198                           Seychelles         98,340
199                      Old and bearded         97,928

[200 rows x 2 columns]

In [77]:
listpa=[]

In [78]:
listpa=listpa+(list(medallas['pais'].unique()))

In [79]:
listpa=listpa+(list(alcohol['Country'].unique()))

In [80]:
listpa=listpa+(list(deaths['country'].unique()))

In [81]:
listpa

['United States',
 'Russia',
 'United Kingdom',
 'China',
 'Germany',
 'France',
 'Italy',
 'Hungary',
 'Japan',
 'Australia',
 'Sweden',
 'Finland',
 'South Korea',
 'Netherlands',
 'Romania',
 'Cuba',
 'Poland',
 'Canada',
 'Norway',
 'Bulgaria',
 'New Zealand',
 'Switzerland',
 'Czechoslovakia',
 'Denmark',
 'Spain',
 'Unified Equipment',
 'Belgium',
 'Turkey',
 'Brazil',
 'Greece',
 'Kenya',
 'Ukraine',
 'Yugoslavia',
 'South Africa',
 'Jamaica',
 'Iran',
 'Ethiopia',
 'Argentina',
 'Austria',
 'North Korea',
 'Kazakhstan',
 'Croatia',
 'Belarus',
 'Mexico',
 'Ireland',
 'Slovakia',
 'Georgia',
 'Estonia',
 'India',
 'Thailand',
 'Uzbekistan',
 'Indonesia',
 'Egypt',
 'Slovenia',
 'Bahamas',
 'Azerbaijan',
 'Morocco',
 'Lithuania',
 'Serbia',
 'Colombia',
 'Portugal',
 'Algeria',
 'Latvia',
 'Venezuela',
 'Uganda',
 'Tunisia',
 'Niger',
 'Trinidad and Tobago',
 'Dominican Republic',
 'Zimbabwe',
 'Pakistan',
 'Ecuador',
 'Israel',
 'Cameroon',
 'Kosovo',
 'Mongolia',
 'Armenia',
 'Chile',
 'Hong Kong',
 'Puerto Rico',
 'Uruguay',
 'Baréin',
 'Taste',
 'Fiji',
 'Philippines',
 'Peru',
 'Vietnam',
 'Singapore',
 'Independent',
 'Costa Rica',
 'Ivory Coast',
 'Syria',
 'Tajikistan',
 'Grenoble',
 'Jordan',
 'Burundi',
 'Luxembourg',
 'Panama',
 'Bermuda',
 'Mozambique',
 'Surinam',
 'United Arab Emirates',
 'Malaysia',
 'Namibia',
 'Kyrgyzstan',
 'Moldova',
 'Lebanon',
 'Saudi Arabia',
 'Iceland',
 'Sri Lanka',
 'Tanzania',
 'Ghana',
 'Bohemia',
 'San Marino',
 'Botswana',
 'Haiti',
 'Macedonia',
 'Zambia',
 'Cyprus',
 'Gabon',
 'Guatemala',
 'Virgin Islands of the United States',
 'Montenegro',
 'Paraguay',
 'Senegal',
 'Sudan',
 'Samoa',
 'Tonga',
 'Turkmenistan',
 'Kuwait',
 'Federation of Western Indies',
 'Afghanistan',
 'Barbados',
 'Burkina Faso',
 'Eritrea',
 'Guyana',
 'Iraq',
 'Mauritius',
 'Togo',
 'Yibouti',
 'Denmark',
 'Switzerland',
 'Iceland',
 'Norway',
 'Finland',
 'Canada',
 'Netherlands',
 'New Zealand',
 'Australia',
 'Sweden',
 'Israel',
 'Austria',
 'United States',
 'Costa Rica',
 'Germany',
 'Brazil',
 'Belgium',
 'Ireland',
 'Luxembourg',
 'Mexico',
 'Singapore',
 'United Kingdom',
 'Chile',
 'Panama',
 'Argentina',
 'Czech Republic',
 'United Arab Emirates',
 'Uruguay',
 'Malta',
 'Colombia',
 'France',
 'Thailand',
 'Qatar',
 'Spain',
 'Guatemala',
 'Suriname',
 'Bahrain',
 'Trinidad and Tobago',
 'Venezuela',
 'Slovakia',
 'El Salvador',
 'Nicaragua',
 'Uzbekistan',
 'Italy',
 'Ecuador',
 'Belize',
 'Japan',
 'Kazakhstan',
 'Moldova',
 'Russian Federation',
 'Poland',
 'South Korea',
 'Bolivia',
 'Lithuania',
 'Belarus',
 'Slovenia',
 'Peru',
 'Turkmenistan',
 'Mauritius',
 'Latvia',
 'Cyprus',
 'Paraguay',
 'Romania',
 'Estonia',
 'Jamaica',
 'Croatia',
 'Turkey',
 'Jordan',
 'Azerbaijan',
 'Philippines',
 'China',
 'Kyrgyzstan',
 'Serbia',
 'Bosnia and Herzegovina',
 'Montenegro',
 'Dominican Republic',
 'Morocco',
 'Hungary',
 'Lebanon',
 'Portugal',
 'Macedonia',
 'Vietnam',
 'Tunisia',
 'Greece',
 'Mongolia',
 'Nigeria',
 'Honduras',
 'Zambia',
 'Albania',
 'Sierra Leone',
 'Namibia',
 'Cameroon',
 'South Africa',
 'Egypt',
 'Armenia',
 'Kenya',
 'Ukraine',
 'Ghana',
 'Dem. Rep. Congo',
 'Georgia',
 'Rep. Congo',
 'Senegal',
 'Bulgaria',
 'Zimbabwe',
 'Malawi',
 'Gabon',
 'Mali',
 'Haiti',
 'Botswana',
 'Comoros',
 "Cote d'Ivoire",
 'Cambodia',
 'Angola',
 'Niger',
 'Chad',
 'Burkina Faso',
 'Madagascar',
 'Tanzania',
 'Liberia',
 'Benin',
 'Togo',
 'Syria',
 'Australia',
 'Austria',
 'Belgium',
 'Britain',
 'Bulgaria',
 'Canada',
 'Chile',
 'Colombia',
 'Croatia',
 'Cyprus',
 'Czech Republic',
 'Denmark',
 'Ecuador',
 'Estonia',
 'Finland',
 'France',
 'Germany',
 'Greece',
 'Guatemala',
 'Hungary',
 'Iceland',
 'Iran',
 'Israel',
 'Italy',
 'Latvia',
 'Lithuania',
 'Luxembourg',
 'Malta',
 'Mexico',
 'Montenegro',
 'Netherlands',
 'New Zealand',
 'Norway',
 'Peru',
 'Poland',
 'Portugal',
 'Romania',
 'Slovakia',
 'Slovenia',
 'South Africa',
 'South Korea',
 'Spain',
 'Sweden',
 'Switzerland',
 'Tunisia',
 'United States']

In [82]:
set(listpa)

{'Afghanistan',
 'Albania',
 'Algeria',
 'Angola',
 'Argentina',
 'Armenia',
 'Australia',
 'Austria',
 'Azerbaijan',
 'Bahamas',
 'Bahrain',
 'Barbados',
 'Baréin',
 'Belarus',
 'Belgium',
 'Belize',
 'Benin',
 'Bermuda',
 'Bohemia',
 'Bolivia',
 'Bosnia and Herzegovina',
 'Botswana',
 'Brazil',
 'Britain',
 'Bulgaria',
 'Burkina Faso',
 'Burundi',
 'Cambodia',
 'Cameroon',
 'Canada',
 'Chad',
 'Chile',
 'China',
 'Colombia',
 'Comoros',
 'Costa Rica',
 "Cote d'Ivoire",
 'Croatia',
 'Cuba',
 'Cyprus',
 'Czech Republic',
 'Czechoslovakia',
 'Dem. Rep. Congo',
 'Denmark',
 'Dominican Republic',
 'Ecuador',
 'Egypt',
 'El Salvador',
 'Eritrea',
 'Estonia',
 'Ethiopia',
 'Federation of Western Indies',
 'Fiji',
 'Finland',
 'France',
 'Gabon',
 'Georgia',
 'Germany',
 'Ghana',
 'Greece',
 'Grenoble',
 'Guatemala',
 'Guyana',
 'Haiti',
 'Honduras',
 'Hong Kong',
 'Hungary',
 'Iceland',
 'Independent',
 'India',
 'Indonesia',
 'Iran',
 'Iraq',
 'Ireland',
 'Israel',
 'Italy',
 'Ivory Coast',
 'Jamaica',
 'Japan',
 'Jordan',
 'Kazakhstan',
 'Kenya',
 'Kosovo',
 'Kuwait',
 'Kyrgyzstan',
 'Latvia',
 'Lebanon',
 'Liberia',
 'Lithuania',
 'Luxembourg',
 'Macedonia',
 'Madagascar',
 'Malawi',
 'Malaysia',
 'Mali',
 'Malta',
 'Mauritius',
 'Mexico',
 'Moldova',
 'Mongolia',
 'Montenegro',
 'Morocco',
 'Mozambique',
 'Namibia',
 'Netherlands',
 'New Zealand',
 'Nicaragua',
 'Niger',
 'Nigeria',
 'North Korea',
 'Norway',
 'Pakistan',
 'Panama',
 'Paraguay',
 'Peru',
 'Philippines',
 'Poland',
 'Portugal',
 'Puerto Rico',
 'Qatar',
 'Rep. Congo',
 'Romania',
 'Russia',
 'Russian Federation',
 'Samoa',
 'San Marino',
 'Saudi Arabia',
 'Senegal',
 'Serbia',
 'Sierra Leone',
 'Singapore',
 'Slovakia',
 'Slovenia',
 'South Africa',
 'South Korea',
 'Spain',
 'Sri Lanka',
 'Sudan',
 'Surinam',
 'Suriname',
 'Sweden',
 'Switzerland',
 'Syria',
 'Tajikistan',
 'Tanzania',
 'Taste',
 'Thailand',
 'Togo',
 'Tonga',
 'Trinidad and Tobago',
 'Tunisia',
 'Turkey',
 'Turkmenistan',
 'Uganda',
 'Ukraine',
 'Unified Equipment',
 'United Arab Emirates',
 'United Kingdom',
 'United States',
 'Uruguay',
 'Uzbekistan',
 'Venezuela',
 'Vietnam',
 'Virgin Islands of the United States',
 'Yibouti',
 'Yugoslavia',
 'Zambia',
 'Zimbabwe'}

In [83]:
listpais=pd.DataFrame(listpa)

In [84]:
listpais

                  0
0     United States
1            Russia
2    United Kingdom
3             China
4           Germany
..              ...
303           Spain
304          Sweden
305     Switzerland
306         Tunisia
307   United States

[308 rows x 1 columns]

In [87]:
listpais.to_csv("listpais.csv", index=False)